/*
Copyright 2023 mark.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	fastdeployv1 "github.com/mark8s/fastdeploy/pkg/apis/fastdeploy/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFastDeploys implements FastDeployInterface
type FakeFastDeploys struct {
	Fake *FakeAppV1
	ns   string
}

var fastdeploysResource = schema.GroupVersionResource{Group: "app.mark8s.io", Version: "v1", Resource: "fastdeploys"}

var fastdeploysKind = schema.GroupVersionKind{Group: "app.mark8s.io", Version: "v1", Kind: "FastDeploy"}

// Get takes name of the fastDeploy, and returns the corresponding fastDeploy object, and an error if there is any.
func (c *FakeFastDeploys) Get(ctx context.Context, name string, options v1.GetOptions) (result *fastdeployv1.FastDeploy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fastdeploysResource, c.ns, name), &fastdeployv1.FastDeploy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fastdeployv1.FastDeploy), err
}

// List takes label and field selectors, and returns the list of FastDeploys that match those selectors.
func (c *FakeFastDeploys) List(ctx context.Context, opts v1.ListOptions) (result *fastdeployv1.FastDeployList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fastdeploysResource, fastdeploysKind, c.ns, opts), &fastdeployv1.FastDeployList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &fastdeployv1.FastDeployList{ListMeta: obj.(*fastdeployv1.FastDeployList).ListMeta}
	for _, item := range obj.(*fastdeployv1.FastDeployList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fastDeploys.
func (c *FakeFastDeploys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fastdeploysResource, c.ns, opts))

}

// Create takes the representation of a fastDeploy and creates it.  Returns the server's representation of the fastDeploy, and an error, if there is any.
func (c *FakeFastDeploys) Create(ctx context.Context, fastDeploy *fastdeployv1.FastDeploy, opts v1.CreateOptions) (result *fastdeployv1.FastDeploy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fastdeploysResource, c.ns, fastDeploy), &fastdeployv1.FastDeploy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fastdeployv1.FastDeploy), err
}

// Update takes the representation of a fastDeploy and updates it. Returns the server's representation of the fastDeploy, and an error, if there is any.
func (c *FakeFastDeploys) Update(ctx context.Context, fastDeploy *fastdeployv1.FastDeploy, opts v1.UpdateOptions) (result *fastdeployv1.FastDeploy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fastdeploysResource, c.ns, fastDeploy), &fastdeployv1.FastDeploy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fastdeployv1.FastDeploy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFastDeploys) UpdateStatus(ctx context.Context, fastDeploy *fastdeployv1.FastDeploy, opts v1.UpdateOptions) (*fastdeployv1.FastDeploy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(fastdeploysResource, "status", c.ns, fastDeploy), &fastdeployv1.FastDeploy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fastdeployv1.FastDeploy), err
}

// Delete takes name of the fastDeploy and deletes it. Returns an error if one occurs.
func (c *FakeFastDeploys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(fastdeploysResource, c.ns, name, opts), &fastdeployv1.FastDeploy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFastDeploys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fastdeploysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &fastdeployv1.FastDeployList{})
	return err
}

// Patch applies the patch and returns the patched fastDeploy.
func (c *FakeFastDeploys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *fastdeployv1.FastDeploy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fastdeploysResource, c.ns, name, pt, data, subresources...), &fastdeployv1.FastDeploy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*fastdeployv1.FastDeploy), err
}
