# permissions for end users to edit fastdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fastdeploy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fastdeploy
    app.kubernetes.io/part-of: fastdeploy
    app.kubernetes.io/managed-by: kustomize
  name: fastdeploy-editor-role
rules:
- apiGroups:
  - app.mark8s.io
  resources:
  - fastdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.mark8s.io
  resources:
  - fastdeploys/status
  verbs:
  - get
