---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.mark8s.io
  resources:
  - fastdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.mark8s.io
  resources:
  - fastdeploys/finalizers
  verbs:
  - update
- apiGroups:
  - app.mark8s.io
  resources:
  - fastdeploys/status
  verbs:
  - get
  - patch
  - update
