apiVersion: app.mark8s.io/v1
kind: FastDeploy
metadata:
  labels:
    app.kubernetes.io/name: fastdeploy
    app.kubernetes.io/instance: fastdeploy-sample
    app.kubernetes.io/part-of: fastdeploy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fastdeploy
  name: fastdeploy-sample
spec:
  name: fast
  namespace: demo
  image: registry.cn-shenzhen.aliyuncs.com/solarmesh/httpbin
  port: 80
  replicas: 1
  enableService: true




