/*
Copyright 2023 mark.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/mark8s/fastdeploy/pkg/apis/fastdeploy/v1"
	scheme "github.com/mark8s/fastdeploy/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FastDeploysGetter has a method to return a FastDeployInterface.
// A group's client should implement this interface.
type FastDeploysGetter interface {
	FastDeploys(namespace string) FastDeployInterface
}

// FastDeployInterface has methods to work with FastDeploy resources.
type FastDeployInterface interface {
	Create(ctx context.Context, fastDeploy *v1.FastDeploy, opts metav1.CreateOptions) (*v1.FastDeploy, error)
	Update(ctx context.Context, fastDeploy *v1.FastDeploy, opts metav1.UpdateOptions) (*v1.FastDeploy, error)
	UpdateStatus(ctx context.Context, fastDeploy *v1.FastDeploy, opts metav1.UpdateOptions) (*v1.FastDeploy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.FastDeploy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FastDeployList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FastDeploy, err error)
	FastDeployExpansion
}

// fastDeploys implements FastDeployInterface
type fastDeploys struct {
	client rest.Interface
	ns     string
}

// newFastDeploys returns a FastDeploys
func newFastDeploys(c *AppV1Client, namespace string) *fastDeploys {
	return &fastDeploys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fastDeploy, and returns the corresponding fastDeploy object, and an error if there is any.
func (c *fastDeploys) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.FastDeploy, err error) {
	result = &v1.FastDeploy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fastdeploys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FastDeploys that match those selectors.
func (c *fastDeploys) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FastDeployList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FastDeployList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fastdeploys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fastDeploys.
func (c *fastDeploys) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fastdeploys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a fastDeploy and creates it.  Returns the server's representation of the fastDeploy, and an error, if there is any.
func (c *fastDeploys) Create(ctx context.Context, fastDeploy *v1.FastDeploy, opts metav1.CreateOptions) (result *v1.FastDeploy, err error) {
	result = &v1.FastDeploy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fastdeploys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fastDeploy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a fastDeploy and updates it. Returns the server's representation of the fastDeploy, and an error, if there is any.
func (c *fastDeploys) Update(ctx context.Context, fastDeploy *v1.FastDeploy, opts metav1.UpdateOptions) (result *v1.FastDeploy, err error) {
	result = &v1.FastDeploy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fastdeploys").
		Name(fastDeploy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fastDeploy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *fastDeploys) UpdateStatus(ctx context.Context, fastDeploy *v1.FastDeploy, opts metav1.UpdateOptions) (result *v1.FastDeploy, err error) {
	result = &v1.FastDeploy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fastdeploys").
		Name(fastDeploy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fastDeploy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the fastDeploy and deletes it. Returns an error if one occurs.
func (c *fastDeploys) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fastdeploys").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fastDeploys) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fastdeploys").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched fastDeploy.
func (c *fastDeploys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FastDeploy, err error) {
	result = &v1.FastDeploy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fastdeploys").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
